/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOVE = 3;
  /** RegularExpression Id. */
  int TURNRIGHT = 4;
  /** RegularExpression Id. */
  int PUT = 5;
  /** RegularExpression Id. */
  int PICK = 6;
  /** RegularExpression Id. */
  int POP = 7;
  /** RegularExpression Id. */
  int DEFVAR = 8;
  /** RegularExpression Id. */
  int EQUALS = 9;
  /** RegularExpression Id. */
  int TURN = 10;
  /** RegularExpression Id. */
  int FACE = 11;
  /** RegularExpression Id. */
  int MOVE_DIR = 12;
  /** RegularExpression Id. */
  int RUN_DIRS = 13;
  /** RegularExpression Id. */
  int MOVE_FACE = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int LOOP = 16;
  /** RegularExpression Id. */
  int REPEAT = 17;
  /** RegularExpression Id. */
  int DEFUN = 18;
  /** RegularExpression Id. */
  int FACING_P = 19;
  /** RegularExpression Id. */
  int CAN_PUT = 20;
  /** RegularExpression Id. */
  int CAN_PICK = 21;
  /** RegularExpression Id. */
  int CAN_MOVE = 22;
  /** RegularExpression Id. */
  int NOT = 23;
  /** RegularExpression Id. */
  int PASS = 24;
  /** RegularExpression Id. */
  int OP = 25;
  /** RegularExpression Id. */
  int CP = 26;
  /** RegularExpression Id. */
  int NUMERO = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int LETRA = 29;
  /** RegularExpression Id. */
  int DIGITO = 30;
  /** RegularExpression Id. */
  int NAME = 31;
  /** RegularExpression Id. */
  int BALLOONS = 32;
  /** RegularExpression Id. */
  int CHIPS = 33;
  /** RegularExpression Id. */
  int RIGHT = 34;
  /** RegularExpression Id. */
  int LEFT = 35;
  /** RegularExpression Id. */
  int AROUND = 36;
  /** RegularExpression Id. */
  int BACK = 37;
  /** RegularExpression Id. */
  int FRONT = 38;
  /** RegularExpression Id. */
  int NORTH = 39;
  /** RegularExpression Id. */
  int SOUTH = 40;
  /** RegularExpression Id. */
  int WEST = 41;
  /** RegularExpression Id. */
  int EAST = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"move\"",
    "\"turnright\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"defvar\"",
    "\"=\"",
    "\"turn\"",
    "\"face\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"if\"",
    "\"loop\"",
    "\"repeat\"",
    "\"defun\"",
    "\"facing-p\"",
    "\"can-put-p\"",
    "\"can-pick-p\"",
    "\"can-move-p\"",
    "\"not\"",
    "\"skip\"",
    "\"(\"",
    "\")\"",
    "<NUMERO>",
    "<DIGIT>",
    "<LETRA>",
    "<DIGITO>",
    "<NAME>",
    "\"balloons\"",
    "\"chips\"",
    "\"right\"",
    "\"left\"",
    "\"around\"",
    "\"back\"",
    "\"front\"",
    "\"north\"",
    "\"south\"",
    "\"west\"",
    "\"east\"",
    "\":\"",
    "\" \"",
    "\"\\n\"",
  };

}
