/* Generated By:JavaCC: Do not edit this line. Robot.java */
package uniandes.lym.robot.control;

import uniandes.lym.robot.kernel.*;
import java.awt.Point;
import java.io.*;
import java.util.Vector;
import java.util.LinkedList;
import java.util.ArrayList;
import java.awt.Point;
//import control.Interpreter;

@SuppressWarnings("serial")
public class Robot implements RobotConstants {


        private RobotWorldDec world;
        private RobotWorld world2;
        //private Interpreter recursividad = new Interpreter();
        private ArrayList<String> variables = new ArrayList<String>();
        private ArrayList<Integer> valorvars = new ArrayList<Integer>();
        private ArrayList<String> tempnombres = new ArrayList<String>();
        private ArrayList<Integer> tempvalores = new ArrayList<Integer>();
        private ArrayList<String> blockfuns = new ArrayList<String>();
        private ArrayList<String> nombrefuns = new ArrayList<String>();
        private ArrayList<String> paramfuns = new ArrayList<String>();
        private ArrayList<String> tempnomdos = new ArrayList<String>();
        private String bloqueuno = "";
        private String bloquedos = "";
        private String blouno = "";
        private String blodos = "";
        private String elreturn = "";
        private String backup = "";
        private String acumuresto = "";
        private String codeloop = "";
        private String condiloop = "";
        private String acumuloop = "";
        private String armando = "";
        //private String nuevotoken = "???";
        private boolean estoyenloop = false;

        private int cuentaif = -1;
        private boolean pruebaif = false;
        void setWorld(RobotWorldDec w) {
                world = (RobotWorldDec) w;
        }
        /*void setWorld2(RobotWorld w2) {
		world2 = (RobotWorld) w2;	
	}*/


        String salida=new String();

  final public boolean command(StringBuffer sistema) throws ParseException {
                int x = 0;
                salida=new String();
                String[] nueva= new String[3];
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP:
      haceInput(x, salida, nueva);
                  //  try {
                //		 Thread.sleep(1);
                  //   } catch (InterruptedException e) {
                        //	        System.err.format("IOException: %s%n", e);
                        //	    }

                        sistema.append(salida);
                        {if (true) return true;}
      break;
    case 44:
      jj_consume_token(44);
               {if (true) return true;}
      break;
    case 0:
      jj_consume_token(0);
                         {if (true) return false;}
      break;
    default:
      jj_la1[0] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void haceInput(int x, String salida, String[] nueva) throws ParseException {
  int p = 0;
  boolean bool;
  int q = 0;
  String busque = "";
  int sizee = 0;
  String cprespuesto = ")";
  String direcciones = "";
    jj_consume_token(OP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
      jj_consume_token(EQUALS);
      jj_consume_token(45);
      cambiarVariable(variables, valorvars);
      break;
    case RUN_DIRS:
      jj_consume_token(RUN_DIRS);
      jj_consume_token(OP);
      jj_consume_token(46);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FRONT:
        jj_consume_token(FRONT);
                                            direcciones = token.image;
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
                                                                                direcciones = token.image;
        break;
      case LEFT:
        jj_consume_token(LEFT);
                                                                                                                   direcciones = token.image;
        break;
      case BACK:
        jj_consume_token(BACK);
                                                                                                                                                      direcciones = token.image;
        break;
      default:
        jj_la1[1] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      label_1:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 47:
          ;
          break;
        default:
          jj_la1[2] = jj_gen;
          break label_1;
        }
        jj_consume_token(47);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FRONT:
          jj_consume_token(FRONT);
          break;
        case RIGHT:
          jj_consume_token(RIGHT);
          break;
        case LEFT:
          jj_consume_token(LEFT);
          break;
        case BACK:
          jj_consume_token(BACK);
          break;
        default:
          jj_la1[3] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
                                                                   direcciones= direcciones.concat(token.image);
                                                                                                System.out.println(direcciones);
      }
      jj_consume_token(CP);
      break;
    case MOVE:
      jj_consume_token(MOVE);
      jj_consume_token(45);
      x = checkNum(variables, valorvars);
                                                              world.moveForward(x);salida = "Command: Moveforward ";
      break;
    case SALTAR:
      jj_consume_token(SALTAR);
      break;
    case TURN:
      jj_consume_token(TURN);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT:
        jj_consume_token(LEFT);
                                      world.turnRight();world.turnRight();world.turnRight();
        break;
      case AROUND:
        jj_consume_token(AROUND);
                                                    world.turnRight();world.turnRight();
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
                                                   world.turnRight();
        break;
      default:
        jj_la1[4] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case FACE:
      jj_consume_token(FACE);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
                                                                if(world.getFacing()==0)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==2)
                                                                {
                                                                 world.turnRight();
                                                                }
                                                                else if(world.getFacing()==3)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
        break;
      case WEST:
        jj_consume_token(WEST);
                                                  if(world.getFacing()==0)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==2)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==1)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight(); world.turnRight();world.turnRight();
                                                                }
        break;
      case EAST:
        jj_consume_token(EAST);
                                                  if(world.getFacing()==0)
                                                                {
                                                                 world.turnRight();
                                                                }
                                                                else if(world.getFacing()==1)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==3)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
        break;
      case NORTH:
        jj_consume_token(NORTH);
                                                    if(world.getFacing()==1)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==2)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==3)
                                                                {
                                                                 world.turnRight();
                                                                }
        break;
      default:
        jj_la1[5] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case PUT:
      jj_consume_token(PUT);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                                        world.putBalloons(x);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                                      world.putChips(x);
        break;
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case PICK:
      jj_consume_token(PICK);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                           world.grabBalloons(x);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                                      world.pickChips(x);
        break;
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case MOVE_DIR:
      jj_consume_token(MOVE_DIR);
      jj_consume_token(45);
      x = checkNum(variables, valorvars);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FRONT:
        jj_consume_token(FRONT);
                                          for(int i=1;i<=x;i++)
                                          { world.down(); }
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
                                          for(int i=1;i<=x;i++)
                                          { world.right(); }
        break;
      case LEFT:
        jj_consume_token(LEFT);
                                          for(int i=1;i<=x;i++)
                                          { world.left(); }
        break;
      case BACK:
        jj_consume_token(BACK);
                                          for(int i=1;i<=x;i++)
                                          { world.up(); }
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case REPEAT:
      jj_consume_token(REPEAT);
      jj_consume_token(45);
      x = checkNum(variables, valorvars);
      jj_consume_token(45);
                                                                      elreturn = "";
      jj_consume_token(OP);
                                               acumuresto = "";
      soloRevisaIf(x, salida, tempnombres, tempvalores);
      jj_consume_token(CP);
                                                System.out.println(elreturn);
      jj_consume_token(CP);
                                          if(!elreturn.equals(""))
                                          {
                                                acumuresto = "(";
                                                for(p=0; p<x;p++)
                                                {
                                                  acumuresto = acumuresto.concat("(");
                                                  acumuresto = acumuresto.concat(elreturn);
                                                  acumuresto = acumuresto.concat(")");
                                                }
                                                acumuresto = acumuresto.concat(")");
                                                elreturn="";
                                          }
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                if(!elreturn.equals(""))
                                                {
                                                        acumuresto = acumuresto.concat("(");
                                                        acumuresto = acumuresto.concat(elreturn);
                                                        acumuresto = acumuresto.concat(")");
                                                }
                                                acumuresto = cprespuesto.concat(acumuresto);
                                                System.out.println(acumuresto);
                                                this.ReInit(new java.io.StringReader(acumuresto));
      break;
    case MOVE_FACE:
      jj_consume_token(MOVE_FACE);
      jj_consume_token(45);
      x = checkNum(variables, valorvars);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
                                                                if(world.getFacing()==0)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==2)
                                                                {
                                                                 world.turnRight();
                                                                }
                                                                else if(world.getFacing()==3)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                for(int i=1;i<=x;i++)
                                                                { world.down(); }
        break;
      case WEST:
        jj_consume_token(WEST);
                                                  if(world.getFacing()==0)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==2)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==1)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight(); world.turnRight();world.turnRight();
                                                                }
                                                                for(int i=1;i<=x;i++)
                                                                { world.left(); }
        break;
      case EAST:
        jj_consume_token(EAST);
                                                  if(world.getFacing()==0)
                                                                {
                                                                 world.turnRight();
                                                                }
                                                                else if(world.getFacing()==1)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==3)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                for(int i=1;i<=x;i++)
                                                                { world.right(); }
        break;
      case NORTH:
        jj_consume_token(NORTH);
                                                    if(world.getFacing()==1)
                                                                {
                                                                 world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==2)
                                                                {
                                                                 world.turnRight();world.turnRight();world.turnRight();
                                                                }
                                                                else if(world.getFacing()==3)
                                                                {
                                                                 world.turnRight();
                                                                }
                                                                for(int i=1;i<=x;i++)
                                                                { world.up(); }
        break;
      default:
        jj_la1[9] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case RESETVAR:
      jj_consume_token(RESETVAR);
                                                sizee = tempnomdos.size();
                                                for(p=0; p<tempnomdos.size(); p++)
                                                {
                                                  busque = tempnomdos.get(q);
                                                  for(q=0; q<variables.size(); q++)
                                                  {
                                                    if(busque.equals(variables.get(q)))
                                                    {
                                                      variables.remove(q);
                                                      valorvars.remove(q);
                                                      tempnomdos.remove(p);
                                                    }
                                                  }
                                                }
      break;
    case DEFVAR:
      jj_consume_token(DEFVAR);
      jj_consume_token(45);
      declararVariable(variables, valorvars);
      break;
    case DEFUN:
      jj_consume_token(DEFUN);
      jj_consume_token(45);
      cargarFuncion(tempnombres, tempvalores, nombrefuns, paramfuns, blockfuns);
      break;
    case IF:
      jj_consume_token(IF);
      bool = condition();
      jj_consume_token(CP);
      jj_consume_token(OP);
                                elreturn=token.image; acumuresto = "";
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                                           bloqueuno=elreturn.concat(")");
      jj_consume_token(CP);
                               elreturn="";
      jj_consume_token(OP);
                                elreturn=token.image;
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                                           bloquedos=elreturn.concat(")");
      jj_consume_token(CP);
                               elreturn="";
      jj_consume_token(CP);
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                          if(!elreturn.equals(""))
                          {
                                acumuresto = "(";
                                acumuresto = acumuresto.concat(elreturn);
                                acumuresto = acumuresto.concat(")");
                          }
                          elreturn="";
                          if (bool)
                          {
                            bloqueuno = cprespuesto.concat(bloqueuno);
                            bloqueuno = bloqueuno.concat(acumuresto);
                            System.out.println(bloqueuno);
                            this.ReInit(new java.io.StringReader(bloqueuno));
                            bloqueuno = "";
                            bloquedos = "";
                            acumuresto = "";
                          }
                          else
                          {
                            bloquedos = cprespuesto.concat(bloquedos);
                            bloquedos = bloquedos.concat(acumuresto);
                            System.out.println(bloquedos);
                            this.ReInit(new java.io.StringReader(bloquedos));
                            bloqueuno = "";
                            bloquedos = "";
                            acumuresto = "";
                          }
      break;
    case LOOP:
      jj_consume_token(LOOP);
                             elreturn = ""; backup= "";
      estoyenloop = condition();
                                          if(elreturn == "")
                                          {
                                            condiloop = backup;
                                          }
                                          else
                                          {
                                            condiloop = elreturn;
                                          }
      jj_consume_token(CP);
      jj_consume_token(OP);
                                                     elreturn=token.image;
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                                                            //elreturn=elreturn.concat(token.image);
                                                                                                                                                elreturn=elreturn.concat(")");
                                                                                                                                                codeloop= elreturn;
      jj_consume_token(CP);
                                               elreturn="";
      jj_consume_token(CP);
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                          acumuloop = acumuloop.concat(elreturn);
                                          elreturn="";
                                          //codeloop=cprespuesto.concat(codeloop);
                                          if(estoyenloop)
                                          {
                                            this.ReInit(new java.io.StringReader(cprespuesto));
                                          }
      break;
    case OP:
      jj_consume_token(OP);
      haceInputRecursion(x, salida, nueva);
      break;
    case LETRA:
      buscarFuncion();
      break;
    default:
      jj_la1[10] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(CP);
          if(estoyenloop)
          {
            armando = codeloop;

            armando = armando.concat("(loop");
            armando = armando.concat(condiloop);
            armando = armando.concat(")");
            armando = armando.concat(codeloop);
            armando = armando.concat(")");
            //armando = armando.concat(codeloop);
            System.out.println(armando);
            this.ReInit(new java.io.StringReader(armando));
          }
          else if(acumuloop!="")
          {
            this.ReInit(new java.io.StringReader(acumuloop));
          }
          else if(acumuloop!="")
          {
            this.ReInit(new java.io.StringReader(acumuloop));
            acumuloop="";
          }
          else
          { }
  }

  final public void haceInputRecursion(int x, String salida, String[] nueva) throws ParseException {
  int p = 0;
  boolean bool;
  int q = 0;
  String busque = "";
  int sizee = 0;
  String cprespuesto=")";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
      jj_consume_token(EQUALS);
      jj_consume_token(45);
      cambiarVariable(variables, valorvars);
      break;
    case MOVE:
      jj_consume_token(MOVE);
      jj_consume_token(45);
      x = checkNum(variables, valorvars);
                                                              world.moveForward(x);salida = "Command: Moveforward ";
      break;
    case SALTAR:
      jj_consume_token(SALTAR);
      break;
    case TURN:
      jj_consume_token(TURN);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT:
        jj_consume_token(LEFT);
                                      world.turnRight();world.turnRight();world.turnRight();
        break;
      case AROUND:
        jj_consume_token(AROUND);
                                                    world.turnRight();world.turnRight();
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
                                                   world.turnRight();
        break;
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case FACE:
      jj_consume_token(FACE);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
        break;
      case WEST:
        jj_consume_token(WEST);
        break;
      case EAST:
        jj_consume_token(EAST);
        break;
      case NORTH:
        jj_consume_token(NORTH);
        break;
      default:
        jj_la1[12] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case PUT:
      jj_consume_token(PUT);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                                        world.putBalloons(x);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                                      world.putChips(x);
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case PICK:
      jj_consume_token(PICK);
      jj_consume_token(47);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                           world.grabBalloons(x);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        jj_consume_token(45);
        x = checkNum(variables, valorvars);
                                                                                      world.pickChips(x);
        break;
      default:
        jj_la1[14] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case MOVE_DIR:
      jj_consume_token(MOVE_DIR);
      x = checkNum(variables, valorvars);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FRONT:
        jj_consume_token(FRONT);
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
        break;
      case LEFT:
        jj_consume_token(LEFT);
        break;
      case BACK:
        jj_consume_token(BACK);
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case REPEAT:
      jj_consume_token(REPEAT);
      jj_consume_token(45);
      x = checkNum(variables, valorvars);
      jj_consume_token(45);
                                                                      elreturn = "";
      jj_consume_token(OP);
                                               acumuresto = "";
      soloRevisaIf(x, salida, tempnombres, tempvalores);
      jj_consume_token(CP);
                                                System.out.println(elreturn);
      jj_consume_token(CP);
                                          if(!elreturn.equals(""))
                                          {
                                                acumuresto = "(";
                                                for(p=0; p<x;p++)
                                                {
                                                  acumuresto = acumuresto.concat("(");
                                                  acumuresto = acumuresto.concat(elreturn);
                                                  acumuresto = acumuresto.concat(")");
                                                }
                                                acumuresto = acumuresto.concat(")");
                                                elreturn="";
                                          }
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                if(!elreturn.equals(""))
                                                {
                                                        acumuresto = acumuresto.concat("(");
                                                        acumuresto = acumuresto.concat(elreturn);
                                                        acumuresto = acumuresto.concat(")");
                                                }
                                                acumuresto = cprespuesto.concat(acumuresto);
                                                System.out.println(acumuresto);
                                                this.ReInit(new java.io.StringReader(acumuresto));
      break;
    case RUN_DIRS:
      jj_consume_token(RUN_DIRS);
      label_2:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FRONT:
          jj_consume_token(FRONT);
          break;
        case RIGHT:
          jj_consume_token(RIGHT);
          break;
        case LEFT:
          jj_consume_token(LEFT);
          break;
        case BACK:
          jj_consume_token(BACK);
          break;
        default:
          jj_la1[16] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RIGHT:
        case LEFT:
        case BACK:
        case FRONT:
          ;
          break;
        default:
          jj_la1[17] = jj_gen;
          break label_2;
        }
      }
      break;
    case MOVE_FACE:
      jj_consume_token(MOVE_FACE);
      x = checkNum(variables, valorvars);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
        break;
      case WEST:
        jj_consume_token(WEST);
        break;
      case EAST:
        jj_consume_token(EAST);
        break;
      case NORTH:
        jj_consume_token(NORTH);
        break;
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case RESETVAR:
      jj_consume_token(RESETVAR);
                                                sizee = tempnomdos.size();
                                                for(p=0; p<tempnomdos.size(); p++)
                                                {
                                                  busque = tempnomdos.get(q);
                                                  for(q=0; q<variables.size(); q++)
                                                  {
                                                    if(busque.equals(variables.get(q)))
                                                    {
                                                      variables.remove(q);
                                                      valorvars.remove(q);
                                                      tempnomdos.remove(p);
                                                    }
                                                  }
                                                }
      break;
    case DEFVAR:
      jj_consume_token(DEFVAR);
      jj_consume_token(45);
      declararVariable(variables, valorvars);
      break;
    case DEFUN:
      jj_consume_token(DEFUN);
      jj_consume_token(45);
      cargarFuncion(tempnombres, tempvalores, nombrefuns, paramfuns, blockfuns);
      break;
    case IF:
      jj_consume_token(IF);
      bool = condition();
      jj_consume_token(CP);
      jj_consume_token(OP);
                                elreturn=token.image; acumuresto = "";
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                                           bloqueuno=elreturn.concat(")");
      jj_consume_token(CP);
                               elreturn="";
      jj_consume_token(OP);
                                elreturn=token.image;
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                                                                           bloquedos=elreturn.concat(")");
      jj_consume_token(CP);
                               elreturn="";
      jj_consume_token(CP);
      soloRevisaIf(x, salida, tempnombres, tempvalores);
                          if(!elreturn.equals(""))
                          {
                                acumuresto = "(";
                                acumuresto = acumuresto.concat(elreturn);
                                acumuresto = acumuresto.concat(")");
                          }
                          elreturn="";
                          if (bool)
                          {
                            bloqueuno = cprespuesto.concat(bloqueuno);
                            bloqueuno = bloqueuno.concat(acumuresto);
                            System.out.println(bloqueuno);
                            this.ReInit(new java.io.StringReader(bloqueuno));
                            bloqueuno = "";
                            bloquedos = "";
                            acumuresto = "";
                          }
                          else
                          {
                            bloquedos = cprespuesto.concat(bloquedos);
                            bloquedos = bloquedos.concat(acumuresto);
                            System.out.println(bloquedos);
                            this.ReInit(new java.io.StringReader(bloquedos));
                            bloqueuno = "";
                            bloquedos = "";
                            acumuresto = "";
                          }
      break;
    case OP:
      jj_consume_token(OP);
      haceInputRecursion(x, salida, nueva);
      break;
    case LETRA:
      buscarFuncion();
      break;
    default:
      jj_la1[19] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(CP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case OP:
      jj_consume_token(OP);
      haceInputRecursion(x, salida, nueva);
      break;
    default:
      jj_la1[20] = jj_gen;
      ;
    }
  }

  final public void buscarFuncion() throws ParseException {
  int x=0;
  int y=0;
  boolean cheker=false;
  int indexxx= 0;
  String elnombre = "";
  String elsupernombre = "";
  int elnumero = 0;
  String input = "";
  String cpp= ")";
    jj_consume_token(LETRA);
                elsupernombre=elsupernombre.concat(token.image);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
      case DIGITO:
        ;
        break;
      default:
        jj_la1[21] = jj_gen;
        break label_3;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
        jj_consume_token(LETRA);
                                                                              elsupernombre=elsupernombre.concat(token.image);
        break;
      case DIGITO:
        jj_consume_token(DIGITO);
                                                                                                                                            elsupernombre=elsupernombre.concat(token.image);
        break;
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    try
                        {
                                for(x=0; x<nombrefuns.size(); x++)
                        {
                                if(elsupernombre.equals(nombrefuns.get(x)))
                                {
                                  cheker=true;
                                  indexxx= x;
                                  input = blockfuns.get(x);
                                  try
                                                {
                                                        tempnombres = new ArrayList<String>();
                                                        tempvalores = new ArrayList<Integer>();
                                                        String[] tempvarss= paramfuns.get(indexxx).split(" ");
                                                        System.out.println(tempvarss.length);
                                                        for(y=0; y<tempvarss.length; y++)
                                                        {
                                                          tempnombres.add(tempvarss[y]);
                                                          tempnomdos.add(tempvarss[y]);
                                                          tempvalores.add(-1);
                                                         }
                                                         if(paramfuns.get(indexxx).equals(""))
                                                         {
                                                           tempnombres.remove(0);
                                                           tempnomdos.remove(tempnomdos.size()-1);
                                                           tempvalores.remove(0);
                                                         }
                                                }
                                        catch (NumberFormatException ee)
                                                {
                                                        // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                                        // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                                        {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                                                }

                                }
                        }
                        if(!cheker)
                        {

                          {if (true) throw new Error("NO ENCONTRE ESA FUNCION... PAILA ");}

                        }
                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                        }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 45:
      jj_consume_token(45);
      jj_consume_token(NUMERO);
      if(tempnombres.get(0)!=null) {
        elnombre = tempnombres.get(0);
        elnumero = Integer.parseInt(token.image);
        tempnombres.remove(0);
        variables.add(elnombre);
        valorvars.add(elnumero);
      }
      else
      {
        {if (true) throw new Error("NO HAY SUFICIENTES VARIABLES");}
      }
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          ;
          break;
        default:
          jj_la1[23] = jj_gen;
          break label_4;
        }
        jj_consume_token(45);
        jj_consume_token(NUMERO);
    if(tempnombres.get(0)!=null) {
        elnombre = tempnombres.get(0);
        elnumero = Integer.parseInt(token.image);
        tempnombres.remove(0);
        variables.add(elnombre);
        valorvars.add(elnumero);
      }
      else
      {
        {if (true) throw new Error("NO HAY SUFICIENTES VARIABLES");}
      }
      }
      break;
    default:
      jj_la1[24] = jj_gen;
      ;
    }
    jj_consume_token(CP);
    if(tempnombres.size() >0)
    {
      {if (true) throw new Error("FALTARON VARIABLE POR DEFINIR PARA USAR LA FUNCION");}
    }
    input = cpp.concat(input);
    //System.out.println(input);
    elreturn = "";
    soloRevisaIf(x, salida, tempnombres, tempvalores);
    if(!elreturn.equals(""))
                          {
                                acumuresto = "(";
                                acumuresto = acumuresto.concat(elreturn);
                                acumuresto = acumuresto.concat(")");
                                if(!paramfuns.get(indexxx).equals(""))
                                {
                                  input = input.concat("(!!!)");
                                }
                                //input = input.concat("(!!!)");
                        input = input.concat(acumuresto);
                          }
    System.out.println("EL NUEVO INPUT ES:   "+input);

    this.ReInit(new java.io.StringReader(input));
    //this.ReInit(new java.io.StringReader(elreturn));

  }

  final public void soloRevisaIf(int x, String salida, ArrayList<String> tempnombres, ArrayList<Integer> tempvalores) throws ParseException {
  int p = 0;
  boolean bool;
  //String elretur = "";
  String amedias = "";
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case EQUALS:
      jj_consume_token(EQUALS);
                            elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                         elreturn=elreturn.concat(token.image);
      cambiarVariable(tempnombres, tempvalores);
      break;
    case MOVE:
      jj_consume_token(MOVE);
                          elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                      elreturn=elreturn.concat(token.image);
      x = checkNum(tempnombres, tempvalores);
      break;
    case SALTAR:
      jj_consume_token(SALTAR);
                            elreturn=elreturn.concat(token.image);
      break;
    case TURN:
      jj_consume_token(TURN);
                          elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                                                       elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LEFT:
        jj_consume_token(LEFT);
        break;
      case AROUND:
        jj_consume_token(AROUND);
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
        break;
      default:
        jj_la1[25] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                        elreturn=elreturn.concat(token.image);
      break;
    case FACE:
      jj_consume_token(FACE);
                          elreturn=elreturn.concat(token.image);
      jj_consume_token(46);
                                                                      elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
        break;
      case WEST:
        jj_consume_token(WEST);
        break;
      case EAST:
        jj_consume_token(EAST);
        break;
      case NORTH:
        jj_consume_token(NORTH);
        break;
      default:
        jj_la1[26] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                              elreturn=elreturn.concat(token.image);
      break;
    case PUT:
      jj_consume_token(PUT);
                         elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                                                      elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        break;
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                    elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                                                                                                                                elreturn=elreturn.concat(token.image);
      x = checkNum(tempnombres, tempvalores);
      break;
    case PICK:
      jj_consume_token(PICK);
                          elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                                                       elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        break;
      default:
        jj_la1[28] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                    elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                                                                                                                                 elreturn=elreturn.concat(token.image);
      x = checkNum(tempnombres, tempvalores);
      break;
    case MOVE_DIR:
      jj_consume_token(MOVE_DIR);
                              elreturn=elreturn.concat(token.image);
      x = checkNum(tempnombres, tempvalores);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case FRONT:
        jj_consume_token(FRONT);
        break;
      case RIGHT:
        jj_consume_token(RIGHT);
        break;
      case LEFT:
        jj_consume_token(LEFT);
        break;
      case BACK:
        jj_consume_token(BACK);
        break;
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                            elreturn=elreturn.concat(token.image);
      break;
    case RUN_DIRS:
      jj_consume_token(RUN_DIRS);
                              elreturn=elreturn.concat(token.image);
      label_5:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case FRONT:
          jj_consume_token(FRONT);
                                                                               elreturn=elreturn.concat(token.image);
          break;
        case RIGHT:
          jj_consume_token(RIGHT);
                                                                                                                                elreturn=elreturn.concat(token.image);
          break;
        case LEFT:
          jj_consume_token(LEFT);
                                                                                                                                                                                elreturn=elreturn.concat(token.image);
          break;
        case BACK:
          jj_consume_token(BACK);
                                                                                                                                                                                                                                elreturn=elreturn.concat(token.image);
          break;
        default:
          jj_la1[30] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case RIGHT:
        case LEFT:
        case BACK:
        case FRONT:
          ;
          break;
        default:
          jj_la1[31] = jj_gen;
          break label_5;
        }
      }
      break;
    case MOVE_FACE:
      jj_consume_token(MOVE_FACE);
                                elreturn=elreturn.concat(token.image);
      x = checkNum(tempnombres, valorvars);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
        break;
      case WEST:
        jj_consume_token(WEST);
        break;
      case EAST:
        jj_consume_token(EAST);
        break;
      case NORTH:
        jj_consume_token(NORTH);
        break;
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                           elreturn=elreturn.concat(token.image);
      break;
    case DEFVAR:
      jj_consume_token(DEFVAR);
                             elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                         elreturn=elreturn.concat(token.image);
      declararVariable(tempnombres, valorvars);
                                                                                                                                                            elreturn=elreturn.concat(token.image);
      break;
    case IF:
      jj_consume_token(IF);
                        elreturn=elreturn.concat(token.image);
      bool = condition();
      break;
    case CAN_MOVE_P:
      jj_consume_token(CAN_MOVE_P);
                                   elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                                                                 elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
        break;
      case WEST:
        jj_consume_token(WEST);
        break;
      case EAST:
        jj_consume_token(EAST);
        break;
      case NORTH:
        jj_consume_token(NORTH);
        break;
      default:
        jj_la1[33] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                                         elreturn=elreturn.concat(token.image);
      break;
    case FACING_P:
      jj_consume_token(FACING_P);
                                  elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                                                               elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
        break;
      case WEST:
        jj_consume_token(WEST);
        break;
      case EAST:
        jj_consume_token(EAST);
        break;
      case NORTH:
        jj_consume_token(NORTH);
        break;
      default:
        jj_la1[34] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                                       elreturn=elreturn.concat(token.image);
      break;
    case CAN_PUT_P:
      jj_consume_token(CAN_PUT_P);
                               elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                           elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
        break;
      default:
        jj_la1[35] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
                                                                                                                                          elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                                                                                                                                      elreturn=elreturn.concat(token.image);
      x = checkNum(tempnombres, tempvalores);
      break;
    case NOT:
      jj_consume_token(NOT);
                            elreturn=elreturn.concat(token.image);
      bool = condition();
      jj_consume_token(CP);
                                                                                           elreturn=elreturn.concat(token.image);
      break;
    case 0:
      jj_consume_token(0);
      break;
    case OP:
      label_6:
      while (true) {
        jj_consume_token(OP);
                          elreturn=elreturn.concat(token.image);
        soloRevisaIf(x, salida, tempnombres, tempvalores);
        jj_consume_token(CP);
                                                                                                                            elreturn=elreturn.concat(token.image);
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case OP:
          ;
          break;
        default:
          jj_la1[36] = jj_gen;
          break label_6;
        }
      }
      break;
    case LETRA:
      chequearFuncion();
      break;
    default:
      jj_la1[37] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void chequearFuncion() throws ParseException {
  String elsupernombre = "";
  int indexxx = 0;
  boolean cheker =false;
  int x = 0;
  int tamanio = 0;
  String momenparams = "";
    jj_consume_token(LETRA);
                elsupernombre=elsupernombre.concat(token.image); elreturn=elreturn.concat(token.image);
    label_7:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
      case DIGITO:
        ;
        break;
      default:
        jj_la1[38] = jj_gen;
        break label_7;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
        jj_consume_token(LETRA);
                                                                                                                     elsupernombre=elsupernombre.concat(token.image); elreturn=elreturn.concat(token.image);
        break;
      case DIGITO:
        jj_consume_token(DIGITO);
                                                                                                                                                                                                                          elsupernombre=elsupernombre.concat(token.image); elreturn=elreturn.concat(token.image);
        break;
      default:
        jj_la1[39] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    for(x=0; x<nombrefuns.size(); x++)
    {
        if(elsupernombre.equals(nombrefuns.get(x)))
        {
          cheker=true;
          indexxx= x;
        }
   }
   if(!cheker)
   {
     {if (true) throw new Error("NO ENCONTRE ESA FUNCION... PAILA ");}

   }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 45:
      jj_consume_token(45);
         elreturn=elreturn.concat(token.image);
      jj_consume_token(NUMERO);
              elreturn=elreturn.concat(token.image); momenparams= momenparams.concat(token.image);
      label_8:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          ;
          break;
        default:
          jj_la1[40] = jj_gen;
          break label_8;
        }
        jj_consume_token(45);
          elreturn=elreturn.concat(token.image); momenparams= momenparams.concat(token.image);
        jj_consume_token(NUMERO);
                elreturn=elreturn.concat(token.image); momenparams= momenparams.concat(token.image);
      }
      break;
    default:
      jj_la1[41] = jj_gen;
      ;
    }
    String[] tempvarsss= paramfuns.get(indexxx).split(" ");
    //System.out.println(tempvarsss.length);
    String[] confirmo= momenparams.split(" ");
    //System.out.println(confirmo.length);
    if(tempvarsss.length!=confirmo.length)
    {
      {if (true) throw new Error("LA CANTIDAD DE PARAMETROS NO COINCIDE CON LA ESPERADA");}
    }
  }

  final public void cargarFuncion(ArrayList<String> tempnombres, ArrayList<Integer> tempvalores, ArrayList<String> nombrefuns, ArrayList<String> paramfuns, ArrayList<String> blockfuns) throws ParseException {
  String parametros = "";
  String agregastr = "";
  int agregaint = 0;
  int x = 0;
  String salida = "";
  String elrelleno = "";
  String elrenombre = "";
    jj_consume_token(LETRA);
                elrenombre=elrenombre.concat(token.image);
    label_9:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
      case DIGITO:
        ;
        break;
      default:
        jj_la1[42] = jj_gen;
        break label_9;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
        jj_consume_token(LETRA);
                                                                        elrenombre=elrenombre.concat(token.image);
        break;
      case DIGITO:
        jj_consume_token(DIGITO);
                                                                                                                                elrenombre=elrenombre.concat(token.image);
        break;
      default:
        jj_la1[43] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    try
                        {
                                nombrefuns.add(elrenombre);
                                System.out.println(elrenombre);

                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                        }
    jj_consume_token(45);
    jj_consume_token(OP);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LETRA:
      jj_consume_token(LETRA);
      label_10:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LETRA:
        case DIGITO:
          ;
          break;
        default:
          jj_la1[44] = jj_gen;
          break label_10;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LETRA:
          jj_consume_token(LETRA);
          break;
        case DIGITO:
          jj_consume_token(DIGITO);
          break;
        default:
          jj_la1[45] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
        try
                        {
                                tempnombres.add(token.image);
                                tempvalores.add(4);
                                parametros = parametros.concat(token.image);
                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                        }
      label_11:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          ;
          break;
        default:
          jj_la1[46] = jj_gen;
          break label_11;
        }
        jj_consume_token(45);
        jj_consume_token(LETRA);
        label_12:
        while (true) {
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case LETRA:
          case DIGITO:
            ;
            break;
          default:
            jj_la1[47] = jj_gen;
            break label_12;
          }
          switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
          case LETRA:
            jj_consume_token(LETRA);
            break;
          case DIGITO:
            jj_consume_token(DIGITO);
            break;
          default:
            jj_la1[48] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
        }
                try
                        {
                                tempnombres.add(token.image);
                                tempvalores.add(4);
                                parametros = parametros.concat(" ");
                                parametros = parametros.concat(token.image);
                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                        }
      }
      break;
    default:
      jj_la1[49] = jj_gen;
      ;
    }
    jj_consume_token(CP);
    for(x=0; x<variables.size(); x++)
    {
      agregastr = variables.get(x);
      agregaint = valorvars.get(x);
      tempnombres.add(agregastr);
          tempvalores.add(agregaint);
     }
     elreturn = "";
     paramfuns.add(parametros);
    jj_consume_token(OP);
           elreturn = token.image;
    soloRevisaIf(x,salida,tempnombres, tempvalores);
    jj_consume_token(CP);
    elreturn = elreturn.concat(token.image);
    System.out.println(parametros);
    blockfuns.add(elreturn);
    System.out.println(elreturn);
  }

  final public int numero() throws ParseException, Error {
                int total=1;
    jj_consume_token(NUMERO);
                        try
                        {
                                total = Integer.parseInt(token.image);
                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("Number out of bounds: "+token.image+"!!");}
                        }
                        {if (true) return total;}
    throw new Error("Missing return statement in function");
  }

  final public boolean condition() throws ParseException {
  int x=0;
  boolean bool;
  int posx=0;
  int posy=0;
  int newpos=0;
  boolean paranot=false;
  boolean parafuncion=false;
    jj_consume_token(OP);
              elreturn=elreturn.concat(token.image);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case FACING_P:
      jj_consume_token(FACING_P);
                            elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                      elreturn=elreturn.concat(token.image);
      bool = facing_p();
                                                 if (bool){{if (true) return true;}}else{{if (true) return false;}}
      break;
    case CAN_PUT_P:
      jj_consume_token(CAN_PUT_P);
                               elreturn=elreturn.concat(token.image);
      jj_consume_token(45);
                                                                           elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case BALLOONS:
        jj_consume_token(BALLOONS);
                                                     elreturn=elreturn.concat(token.image);
        jj_consume_token(45);
                                                                                                 elreturn=elreturn.concat(token.image);
        x = checkNum(variables, valorvars);
                                                                if(world.getMyBalloons() >= x)
                                                                {
                                                                  {if (true) return true;}
                                                                }
                                                                else
                                                                {
                                                                  {if (true) return false;}
                                                                }
        break;
      case CHIPS:
        jj_consume_token(CHIPS);
                                                  elreturn=elreturn.concat(token.image);
        jj_consume_token(45);
                                                                                              elreturn=elreturn.concat(token.image);
        x = checkNum(variables, valorvars);
                                                        if(world.getMyChips() >= x && world.freeSpacesForChips() >= x)
                                                        {
                                                          {if (true) return true;}
                                                        }
                                                        else
                                                        {
                                                          {if (true) return false;}
                                                         }
        break;
      default:
        jj_la1[50] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case CAN_MOVE_P:
      jj_consume_token(CAN_MOVE_P);
                                elreturn=elreturn.concat(token.image);
      jj_consume_token(47);
                                                                             elreturn=elreturn.concat(token.image);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SOUTH:
        jj_consume_token(SOUTH);
                                          elreturn=elreturn.concat(token.image);
                                          posx = (int)world.getPosition().getX();
                                          posy=(int)world.getPosition().getY();
                                          newpos = posy+1;
                                          //System.out.println(newpos);
                                          if(newpos<1)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(newpos >8)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(!world.blockedInRange(posx,posy,newpos,1))
                                          {
                                            {if (true) return true;}
                                          }
                                           else
                                          {
                                            {if (true) return false;}
                                          }
        break;
      case WEST:
        jj_consume_token(WEST);
                                      elreturn=elreturn.concat(token.image);
                                      posx = (int)world.getPosition().getX();
                                          posy=(int)world.getPosition().getY();
                                          newpos = posx-1;
                                          if(newpos<1)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(newpos >8)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(!world.blockedInRange(posx,posy,newpos,3))
                                          {
                                            {if (true) return true;}
                                          }
                                           else
                                          {
                                            {if (true) return false;}
                                          }
        break;
      case EAST:
        jj_consume_token(EAST);
                                          elreturn=elreturn.concat(token.image);
                                          posx = (int)world.getPosition().getX();
                                          posy=(int)world.getPosition().getY();
                                          newpos = posx+1;
                                          if(newpos<1)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(newpos >8)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(!world.blockedInRange(posx,posy,newpos,2))
                                          {
                                            {if (true) return true;}
                                          }
                                           else
                                          {
                                            {if (true) return false;}
                                          }
        break;
      case NORTH:
        jj_consume_token(NORTH);
                                      elreturn=elreturn.concat(token.image);
                                          posx = (int)world.getPosition().getX();
                                          posy=(int)world.getPosition().getY();
                                          newpos = posy-1;
                                          if(newpos<1)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(newpos >8)
                                          {
                                            {if (true) return false;}
                                          }
                                          if(!world.blockedInRange(posx,posy,newpos,0))
                                          {
                                            {if (true) return true;}
                                          }
                                           else
                                          {
                                            {if (true) return false;}
                                          }
        break;
      default:
        jj_la1[51] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case NOT:
      jj_consume_token(NOT);
                 elreturn=elreturn.concat(token.image);
      paranot = condition();
      jj_consume_token(CP);
                                                                elreturn=elreturn.concat(token.image);
                                                                if(paranot)
                                                                {
                                                                  {if (true) return false;}
                                                                }
                                                                else
                                                                {
                                                                  {if (true) return true;}
                                                                }
      break;
    case LETRA:
      parafuncion = buscarFuncionIf();
                                          {if (true) return parafuncion;}
      break;
    default:
      jj_la1[52] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public boolean facing_p() throws ParseException {
  int x=1;
  boolean bool;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case SOUTH:
      jj_consume_token(SOUTH);
    elreturn=elreturn.concat(token.image);
    if (world.facingSouth())
          {

            bool=true;
            {if (true) return bool;}

          }
        else
        {
                 bool=false;
            {if (true) return bool;}
        }
      break;
    case WEST:
      jj_consume_token(WEST);
         elreturn=elreturn.concat(token.image);
          if (world.facingWest())
                  {
                     bool=true;
                 {if (true) return bool;}
                  }
                else
                {
                         bool=false;
                {if (true) return bool;}
                }
      break;
    case EAST:
      jj_consume_token(EAST);
         elreturn=elreturn.concat(token.image);
          if (world.facingEast())
                  {
                     bool=true;
                 {if (true) return bool;}
                  }
                else
                {
                         bool=false;
                {if (true) return bool;}
                }
      break;
    case NORTH:
      jj_consume_token(NORTH);
         elreturn=elreturn.concat(token.image);
          if (world.facingNorth())
                  {
                    bool=true;
                 {if (true) return bool;}
                  }
         else
         {
                 bool=false;
            {if (true) return bool;}
     }
      break;
    default:
      jj_la1[53] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void cambiarVariable(ArrayList<String> variables, ArrayList<Integer> valorvars) throws ParseException {
  int pos=-40;
  int i = 0;
  String pru = "";
    jj_consume_token(LETRA);
               elreturn= elreturn.concat(token.image);
    label_13:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
      case DIGITO:
        ;
        break;
      default:
        jj_la1[54] = jj_gen;
        break label_13;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
        jj_consume_token(LETRA);
                                                                    elreturn=elreturn.concat(token.image);
        break;
      case DIGITO:
        jj_consume_token(DIGITO);
                                                                                                                        elreturn=elreturn.concat(token.image);
        break;
      default:
        jj_la1[55] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    for(i=0; i<variables.size(); i++)
        {
          pru = variables.get(i);
          if (pru!=null)
          {
        if(token.image.equals(pru))
        {
          variables.remove(i);
          valorvars.remove(i);
          variables.add(token.image);
          pos = i;
        }
          }
        }
        if(pos==-40)
        {
          {if (true) throw new Error("ERROR: NO EXISTE LA VARIABLE");}

        }
    jj_consume_token(45);
       elreturn=elreturn.concat(token.image);
    jj_consume_token(NUMERO);
    valorvars.add(Integer.parseInt(token.image));
    elreturn=elreturn.concat(token.image);
  }

  final public int checkNum(ArrayList<String> variables, ArrayList<Integer> valorvars) throws ParseException {
  int rta = -57;
  int i = 0;
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case LETRA:
      jj_consume_token(LETRA);
                elreturn=elreturn.concat(token.image);
      label_14:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LETRA:
        case DIGITO:
          ;
          break;
        default:
          jj_la1[56] = jj_gen;
          break label_14;
        }
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case LETRA:
          jj_consume_token(LETRA);
                                                                    elreturn=elreturn.concat(token.image);
          break;
        case DIGITO:
          jj_consume_token(DIGITO);
                                                                                                                        elreturn=elreturn.concat(token.image);
          break;
        default:
          jj_la1[57] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
      }
        for(i=0; i<variables.size(); i++)
        {
        if(token.image.equals(variables.get(i)))
        {
          rta= valorvars.get(i);

        }
        }
        if(rta == -57)
        {
          {if (true) throw new Error("ERROR: NO EXISTE LA VARIABLE" + token.image);}

        }
        {if (true) return rta;}
      break;
    case NUMERO:
      jj_consume_token(NUMERO);
          rta=Integer.parseInt(token.image);
          elreturn=elreturn.concat(token.image);
          {if (true) return rta;}
      break;
    default:
      jj_la1[58] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    throw new Error("Missing return statement in function");
  }

  final public void declararVariable(ArrayList<String> variables, ArrayList<Integer> valorvars) throws ParseException {
          String nombre = "";
          int total = 1;
          int pos = 0;
          int j = 0;
          int k = 0;
    jj_consume_token(LETRA);
                        elreturn=elreturn.concat(token.image);
    label_15:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
      case DIGITO:
        ;
        break;
      default:
        jj_la1[59] = jj_gen;
        break label_15;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
        jj_consume_token(LETRA);
                                                                            elreturn=elreturn.concat(token.image);
        break;
      case DIGITO:
        jj_consume_token(DIGITO);
                                                                                                                                elreturn=elreturn.concat(token.image);
        break;
      default:
        jj_la1[60] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
            try
                        {
                                variables.add(token.image);

                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                        }
    jj_consume_token(45);
    jj_consume_token(NUMERO);
                        try
                        {
                          total = Integer.parseInt(token.image);
                          valorvars.add(total);



                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("Number out of bounds: "+token.image+"!!");}
                        }
  }

  final public boolean buscarFuncionIf() throws ParseException {
  int x=0;
  int y=0;
  boolean cheker=false;
  int indexxx= 0;
  String elnombre = "";
  String elsupernombre = "";
  int elnumero = 0;
  String input = "";
  String cpp= ")";
    jj_consume_token(LETRA);
                elsupernombre=elsupernombre.concat(token.image); elreturn=elreturn.concat(token.image);
    label_16:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
      case DIGITO:
        ;
        break;
      default:
        jj_la1[61] = jj_gen;
        break label_16;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case LETRA:
        jj_consume_token(LETRA);
                                                                                                                     elsupernombre=elsupernombre.concat(token.image); elreturn=elreturn.concat(token.image);
        break;
      case DIGITO:
        jj_consume_token(DIGITO);
                                                                                                                                                                                                                          elsupernombre=elsupernombre.concat(token.image); elreturn=elreturn.concat(token.image);
        break;
      default:
        jj_la1[62] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    try
                        {
                                for(x=0; x<nombrefuns.size(); x++)
                        {
                                if(elsupernombre.equals(nombrefuns.get(x)))
                                {
                                  cheker=true;
                                  indexxx= x;
                                  input = blockfuns.get(x);
                                  try
                                                {
                                                        tempnombres = new ArrayList<String>();
                                                        tempvalores = new ArrayList<Integer>();
                                                        String[] tempvarss= paramfuns.get(indexxx).split(" ");
                                                        System.out.println(tempvarss.length);
                                                        for(y=0; y<tempvarss.length; y++)
                                                        {
                                                          tempnombres.add(tempvarss[y]);
                                                          tempnomdos.add(tempvarss[y]);
                                                          tempvalores.add(-1);
                                                         }
                                                         if(paramfuns.get(indexxx).equals(""))
                                                         {
                                                           tempnombres.remove(0);
                                                           tempnomdos.remove(tempnomdos.size()-1);
                                                           tempvalores.remove(0);
                                                         }
                                                }
                                        catch (NumberFormatException ee)
                                                {
                                                        // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                                        // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                                        {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                                                }

                                }
                        }
                        if(!cheker)
                        {

                          {if (true) throw new Error("NO ENCONTRE ESA FUNCION... PAILA ");}

                        }
                        }
                        catch (NumberFormatException ee)
                        {
                                // Dada la forma de NUMERO, sabemos que solo puede tener d�gitos
                                // Por lo tanto, lo unico que podria pasar es que el numero sea muy grande
                                {if (true) throw new Error("NO PUDE METER EN EL ARRAY ESTO: "+token.image+"!!");}
                        }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case 45:
      jj_consume_token(45);
         elreturn=elreturn.concat(token.image);
      jj_consume_token(NUMERO);
                elreturn=elreturn.concat(token.image);
      if(tempnombres.get(0)!=null) {
        elnombre = tempnombres.get(0);
        elnumero = Integer.parseInt(token.image);
        tempnombres.remove(0);
        variables.add(elnombre);
        valorvars.add(elnumero);
      }
      else
      {
        {if (true) throw new Error("NO HAY SUFICIENTES VARIABLES");}
      }
      label_17:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case 45:
          ;
          break;
        default:
          jj_la1[63] = jj_gen;
          break label_17;
        }
        jj_consume_token(45);
          elreturn=elreturn.concat(token.image);
        jj_consume_token(NUMERO);
      elreturn=elreturn.concat(token.image);
      backup= elreturn;
    if(tempnombres.get(0)!=null) {
        elnombre = tempnombres.get(0);
        elnumero = Integer.parseInt(token.image);
        tempnombres.remove(0);
        variables.add(elnombre);
        valorvars.add(elnumero);
      }
      else
      {
        {if (true) throw new Error("NO HAY SUFICIENTES VARIABLES");}
      }
      }
      break;
    default:
      jj_la1[64] = jj_gen;
      ;
    }
    jj_consume_token(CP);
    if(tempnombres.size() >0)
    {
      {if (true) throw new Error("FALTARON VARIABLE POR DEFINIR PARA USAR LA FUNCION");}
    }
    //input = nuevotoken.concat(input);

    //input = input.concat(cpp);

    //System.out.println(input);
    elreturn = "";
    jj_consume_token(OP);
          elreturn=elreturn.concat(token.image);
    soloRevisaIf(x, salida, tempnombres, tempvalores);
    jj_consume_token(CP);
          elreturn=elreturn.concat(token.image); blouno = elreturn; elreturn = "";System.out.println("EL PRIMER BLOQUE ES:   "+blouno);
    jj_consume_token(OP);
          elreturn=elreturn.concat(token.image);
    soloRevisaIf(x, salida, tempnombres, tempvalores);
    jj_consume_token(CP);
          elreturn=elreturn.concat(token.image); blodos = elreturn; elreturn = "";System.out.println("EL SEGUNDO BLOQUE ES:   "+blodos);
    jj_consume_token(CP);
    soloRevisaIf(x, salida, tempnombres, tempvalores);
    if(!elreturn.equals(""))
                          {
                                acumuresto = "";
                                acumuresto = acumuresto.concat(blouno);
                                acumuresto = acumuresto.concat(blodos);
                                acumuresto = acumuresto.concat(")");
                                acumuresto = acumuresto.concat(elreturn);
                                if(!paramfuns.get(indexxx).equals(""))
                                {
                                  input = input.concat("(!!!)");
                                }
                                //input = input.concat("(!!!)");
                        input = input.concat(acumuresto);
                          }
    System.out.println("EL NUEVO INPUT ES:   "+input);

    this.ReInit(new java.io.StringReader(input));
    elreturn = "";
    //this.ReInit(new java.io.StringReader(elreturn));

    pruebaif = condition();
                         {if (true) return pruebaif;}
    throw new Error("Missing return statement in function");
  }

  /** Generated Token Manager. */
  public RobotTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[65];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
      jj_la1_init_0();
      jj_la1_init_1();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x1000001,0x80000000,0x0,0x80000000,0x80000000,0x0,0x60000000,0x60000000,0x80000000,0x0,0x1507ffd0,0x80000000,0x0,0x60000000,0x60000000,0x80000000,0x80000000,0x80000000,0x0,0x1506ffd0,0x1000000,0x0,0x0,0x0,0x0,0x80000000,0x0,0x60000000,0x60000000,0x80000000,0x80000000,0x80000000,0x0,0x0,0x0,0x60000000,0x1000000,0x11d8ffd1,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x60000000,0x0,0xd80000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,};
   }
   private static void jj_la1_init_1() {
      jj_la1_1 = new int[] {0x1000,0xd,0x8000,0xd,0x3,0xf0,0x0,0x0,0xd,0xf0,0x400,0x3,0xf0,0x0,0x0,0xd,0xd,0xd,0xf0,0x400,0x0,0xc00,0xc00,0x2000,0x2000,0x3,0xf0,0x0,0x0,0xd,0xd,0xd,0xf0,0xf0,0xf0,0x0,0x0,0x400,0xc00,0xc00,0x2000,0x2000,0xc00,0xc00,0xc00,0xc00,0x2000,0xc00,0xc00,0x400,0x0,0xf0,0x400,0xf0,0xc00,0xc00,0xc00,0xc00,0x500,0xc00,0xc00,0xc00,0xc00,0x2000,0x2000,};
   }

  /** Constructor with InputStream. */
  public Robot(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Robot(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 65; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 65; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Robot(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new RobotTokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 65; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 65; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Robot(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 65; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(RobotTokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 65; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[48];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 65; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
          if ((jj_la1_1[i] & (1<<j)) != 0) {
            la1tokens[32+j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 48; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
