/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_MOVER = 3;
  /** RegularExpression Id. */
  int T_TURNRIGHT = 4;
  /** RegularExpression Id. */
  int T_PONER = 5;
  /** RegularExpression Id. */
  int T_RECOGER = 6;
  /** RegularExpression Id. */
  int T_POP = 7;
  /** RegularExpression Id. */
  int T_RETRO = 8;
  /** RegularExpression Id. */
  int DEFVAR = 9;
  /** RegularExpression Id. */
  int T_BALLOONS = 10;
  /** RegularExpression Id. */
  int T_CHIPS = 11;
  /** RegularExpression Id. */
  int NUMERO = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int letra = 14;
  /** RegularExpression Id. */
  int digito = 15;
  /** RegularExpression Id. */
  int NAME = 16;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\r\"",
    "\"\\t\"",
    "\"move\"",
    "\"TURNRIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"retro\"",
    "\"defvar\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "<NUMERO>",
    "<DIGIT>",
    "<letra>",
    "<digito>",
    "<NAME>",
    "\"(\"",
    "\")\"",
    "\" \"",
    "\"\\n\"",
    "\",\"",
  };

}
